- hosts: all
  become: yes
  vars:
    packages:
      - vim
      - httpd
  tasks:
    - name: Install several useful packages
      dnf:
        name: "{{ packages }}"
        state: latest
    - name: Start Apache service
      service:
        name: httpd
        state: started
    - name: Finished
      debug:
        msg: Apache successfully installed and running
