pipeline {
	agent any
	stages {
		stage("build") {
			steps {
				dir("jenkins-go") {
					sh "go version"
					sh "go fmt ./..."
					sh "go install"
					sh "go run main.go"
				}
			}
		}
		stage("test") {
			steps {
				dir("jenkins-go") {
					sh "go test -v ./..."
				}
			}
		}
	}
}
