pipeline {
	agent {
		docker {
		    image "golang:latest"
		    args "-u root --privileged"
		}
	}
	stages {
		stage("build") {
			steps {
				dir("jenkins-go") {
					sh "go version"
					sh "go fmt ./..."

					// set an upper limit on the timeout for a step
					timeout(time: 60, unit: "SECONDS") {
					    sh "sleep 45"
					}

					// set a limit on the number of retries for a step
					retry(5) {
					    sh "go run build.go"
					}
				}
			}
		}
		stage("test") {
			steps {
				dir("jenkins-go") {
					sh "go test -v ./..."
				}
			}
		}
	}
	post {
		always {
			echo "Jenkins finished"
		}
		success {
			echo "The build was successful"
		}
		failure {
			echo "The build failed"
		}
	}
}
